import { useState, useEffect, useCallback, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import AppLayout from '../components/layout/AppLayout';
import { datasetApi, aiApi, dashboardApi } from '../services/api';
import {
  HiOutlineUpload, HiOutlineTrash, HiOutlineEye, HiOutlineTable, HiOutlineX,
  HiOutlineSearch, HiOutlineChevronUp, HiOutlineChevronDown, HiOutlineChartBar,
  HiOutlineSparkles,
} from 'react-icons/hi';

const PAGE_SIZE = 20;

export default function DatasetsPage() {
  const [datasets, setDatasets] = useState([]);
  const [loading, setLoading] = useState(true);
  const [uploading, setUploading] = useState(false);
  const [dragOver, setDragOver] = useState(false);
  const [preview, setPreview] = useState(null);
  const [previewLoading, setPreviewLoading] = useState(false);
  const [activeTab, setActiveTab] = useState('data'); // 'data' | 'profile'

  // Search, sort, pagination
  const [searchQuery, setSearchQuery] = useState('');
  const [sortCol, setSortCol] = useState(null);
  const [sortDir, setSortDir] = useState('asc');
  const [currentPage, setCurrentPage] = useState(1);
  const [aiSummary, setAiSummary] = useState('');
  const [summaryLoading, setSummaryLoading] = useState(false);
  const [generatingDashboard, setGeneratingDashboard] = useState(false);
  const navigate = useNavigate();

  const fetchDatasets = useCallback(async () => {
    try {
      const res = await datasetApi.getAll();
      setDatasets(res.data);
    } catch (err) {
      console.error('Failed to fetch datasets', err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchDatasets(); }, [fetchDatasets]);

  const handleUpload = async (file) => {
    if (!file) return;
    const validTypes = ['.csv', '.xlsx', '.xls'];
    const ext = '.' + file.name.split('.').pop().toLowerCase();
    if (!validTypes.includes(ext)) {
      alert('Please upload a CSV or Excel file');
      return;
    }
    setUploading(true);
    try {
      await datasetApi.upload(file);
      fetchDatasets();
    } catch (err) {
      alert(err.response?.data?.error || 'Upload failed');
    } finally {
      setUploading(false);
    }
  };

  const handleDelete = async (id) => {
    if (!confirm('Delete this dataset?')) return;
    try {
      await datasetApi.delete(id);
      setDatasets(ds => ds.filter(d => d.id !== id));
      if (preview?.dataset?.id === id) setPreview(null);
    } catch (err) {
      alert('Delete failed');
    }
  };

  const handlePreview = async (id) => {
    setPreviewLoading(true);
    setSearchQuery('');
    setSortCol(null);
    setCurrentPage(1);
    setActiveTab('data');
    try {
      const res = await datasetApi.getPreview(id);
      setPreview(res.data);
    } catch (err) {
      alert('Preview failed');
    } finally {
      setPreviewLoading(false);
    }
  };

  const onDrop = (e) => {
    e.preventDefault();
    setDragOver(false);
    const file = e.dataTransfer.files[0];
    if (file) handleUpload(file);
  };

  // --- Preview data processing ---
  const processedRows = useMemo(() => {
    if (!preview?.rows) return [];
    let rows = [...preview.rows];

    // Search
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      rows = rows.filter(row =>
        Object.values(row).some(v => v != null && String(v).toLowerCase().includes(q))
      );
    }

    // Sort
    if (sortCol) {
      rows.sort((a, b) => {
        const aVal = a[sortCol] ?? '';
        const bVal = b[sortCol] ?? '';
        const numA = Number(aVal);
        const numB = Number(bVal);
        const isNum = !isNaN(numA) && !isNaN(numB);
        if (isNum) return sortDir === 'asc' ? numA - numB : numB - numA;
        return sortDir === 'asc'
          ? String(aVal).localeCompare(String(bVal))
          : String(bVal).localeCompare(String(aVal));
      });
    }

    return rows;
  }, [preview?.rows, searchQuery, sortCol, sortDir]);

  const totalPages = Math.max(1, Math.ceil(processedRows.length / PAGE_SIZE));
  const pagedRows = processedRows.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE);

  const handleSort = (colName) => {
    if (sortCol === colName) {
      setSortDir(d => d === 'asc' ? 'desc' : 'asc');
    } else {
      setSortCol(colName);
      setSortDir('asc');
    }
    setCurrentPage(1);
  };

  const handleAutoGenerateDashboard = async () => {
    if (!preview?.dataset) return;
    setGeneratingDashboard(true);
    try {
      const { dataset, rows } = preview;
      const columns = dataset.columns.map(c => ({ name: c.name, dataType: c.dataType }));
      const sampleRows = rows.slice(0, 10);
      
      // 1. Get AI suggestions
      const res = await aiApi.suggest(columns, sampleRows, dataset.id);
      const suggestions = res.data;

      if (!Array.isArray(suggestions) || suggestions.length === 0) {
        throw new Error('AI could not suggest any charts for this dataset.');
      }

      // 2. Create a new dashboard
      const dashRes = await dashboardApi.create(`AI Dashboard - ${dataset.name}`);
      const newDashboard = dashRes.data;

      // 3. Transform suggestions to widgets
      const widgets = suggestions.map((s, index) => {
        const widgetId = `widget_${Date.now()}_${index}`;
        return {
          widgetId,
          widgetType: s.widgetType || 'BAR',
          title: s.title || `Chart ${index + 1}`,
          config: {
            datasetId: dataset.id,
            xAxis: s.xAxis,
            yAxis: s.yAxis,
            aggregation: s.aggregation || 'SUM',
          },
          position: {
            i: widgetId,
            x: (index % 2) * 6,
            y: Math.floor(index / 2) * 4,
            w: 6,
            h: 4,
            minW: 2,
            minH: 2,
          },
        };
      });

      // 4. Update the dashboard with widgets
      await dashboardApi.update(newDashboard.id, {
        ...newDashboard,
        widgets
      });

      // 5. Redirect to the new dashboard
      navigate(`/dashboard/${newDashboard.id}`);
    } catch (err) {
      console.error('Failed to auto-generate dashboard', err);
      alert(err.message || 'Failed to auto-generate dashboard');
    } finally {
      setGeneratingDashboard(false);
    }
  };

  // --- Data Profiling ---
  const profileStats = useMemo(() => {
    if (!preview?.rows || !preview?.dataset?.columns) return [];
    return preview.dataset.columns.map(col => {
      const values = preview.rows.map(r => r[col.name]);
      const nonNull = values.filter(v => v != null && v !== '');
      const nullCount = values.length - nonNull.length;
      if (col.dataType === 'NUMBER') {
        const nums = nonNull.map(Number).filter(n => !isNaN(n));
        const min = nums.length ? Math.min(...nums) : null;
        const max = nums.length ? Math.max(...nums) : null;
        const avg = nums.length ? nums.reduce((a, b) => a + b, 0) / nums.length : null;
        return {
          name: col.name,
          type: col.dataType,
          nullCount,
          total: values.length,
          min: min?.toLocaleString(undefined, { maximumFractionDigits: 2 }),
          max: max?.toLocaleString(undefined, { maximumFractionDigits: 2 }),
          avg: avg?.toLocaleString(undefined, { maximumFractionDigits: 2 }),
          unique: new Set(nonNull.map(String)).size,
        };
      } else {
        const unique = new Set(nonNull.map(String));
        const freq = {};
        nonNull.forEach(v => { const s = String(v); freq[s] = (freq[s] || 0) + 1; });
        const topEntry = Object.entries(freq).sort((a, b) => b[1] - a[1])[0];
        return {
          name: col.name,
          type: col.dataType,
          nullCount,
          total: values.length,
          unique: unique.size,
          topValue: topEntry ? `"${topEntry[0]}"` : null,
          topCount: topEntry ? topEntry[1] : 0,
        };
      }
    });
  }, [preview]);

  const typeColors = {
    NUMBER: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400',
    STRING: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400',
  };

  return (
    <AppLayout>
      <div className="space-y-8 animate-fade-in">
        {/* Header */}
        <div>
          <h1 className="text-3xl font-bold text-surface-900 dark:text-white">Datasets</h1>
          <p className="text-surface-500 dark:text-surface-400 mt-1">Upload and manage your data files</p>
        </div>

        {/* Upload Zone */}
        <div
          onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
          onDragLeave={() => setDragOver(false)}
          onDrop={onDrop}
          className={`relative border-2 border-dashed rounded-2xl p-12 text-center transition-all duration-300 ${
            dragOver
              ? 'border-primary-400 bg-primary-50 dark:bg-primary-900/20'
              : 'border-surface-300 dark:border-surface-600 hover:border-primary-300 dark:hover:border-primary-700'
          }`}
        >
          {uploading ? (
            <div className="flex flex-col items-center gap-3">
              <div className="w-12 h-12 border-4 border-primary-200 border-t-primary-500 rounded-full animate-spin" />
              <p className="text-surface-600 dark:text-surface-400 font-medium">Uploading & parsing data...</p>
            </div>
          ) : (
            <>
              <div className="inline-flex items-center justify-center w-16 h-16 bg-primary-100 dark:bg-primary-900/30 rounded-2xl mb-4">
                <HiOutlineUpload className="w-8 h-8 text-primary-500" />
              </div>
              <p className="text-lg font-semibold text-surface-700 dark:text-surface-300">
                Drag & drop your file here
              </p>
              <p className="text-surface-400 mt-1 mb-4">Supports CSV and Excel files</p>
              <label className="btn-primary cursor-pointer inline-block">
                Browse Files
                <input
                  type="file"
                  accept=".csv,.xlsx,.xls"
                  onChange={(e) => handleUpload(e.target.files[0])}
                  className="hidden"
                />
              </label>
            </>
          )}
        </div>

        {/* Dataset List */}
        {loading ? (
          <div className="flex justify-center py-12">
            <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-primary-500" />
          </div>
        ) : datasets.length === 0 ? (
          <div className="text-center py-16">
            <HiOutlineTable className="w-16 h-16 text-surface-300 dark:text-surface-600 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-surface-500 dark:text-surface-400">No datasets yet</h3>
            <p className="text-surface-400 dark:text-surface-500 mt-1">Upload a CSV or Excel file to get started</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {datasets.map((ds) => (
              <div key={ds.id} className="card p-5 group">
                <div className="flex items-start justify-between mb-3">
                  <div className="flex-1 min-w-0">
                    <h3 className="font-semibold text-surface-900 dark:text-white truncate">{ds.name}</h3>
                    <p className="text-sm text-surface-400 dark:text-surface-500 mt-1">{ds.fileName}</p>
                  </div>
                  <div className="flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button onClick={() => handlePreview(ds.id)} className="p-2 rounded-lg hover:bg-surface-100 dark:hover:bg-surface-700 text-surface-500" title="Preview">
                      <HiOutlineEye className="w-4 h-4" />
                    </button>
                    <button onClick={() => handleDelete(ds.id)} className="p-2 rounded-lg hover:bg-red-50 dark:hover:bg-red-900/20 text-surface-500 hover:text-red-500" title="Delete">
                      <HiOutlineTrash className="w-4 h-4" />
                    </button>
                  </div>
                </div>
                <div className="flex items-center gap-3 text-sm text-surface-500 dark:text-surface-400 mb-3">
                  <span>{ds.rowCount?.toLocaleString()} rows</span>
                  <span>•</span>
                  <span>{ds.columns?.length} columns</span>
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {ds.columns?.slice(0, 5).map((col, i) => (
                    <span key={i} className={`text-xs px-2 py-0.5 rounded-full font-medium ${typeColors[col.dataType] || typeColors.STRING}`}>
                      {col.name}
                    </span>
                  ))}
                  {ds.columns?.length > 5 && (
                    <span className="text-xs px-2 py-0.5 rounded-full bg-surface-100 dark:bg-surface-700 text-surface-500">
                      +{ds.columns.length - 5} more
                    </span>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Preview Modal */}
        {preview && (
          <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4" onClick={() => setPreview(null)}>
            <div className="bg-white dark:bg-surface-800 rounded-2xl shadow-2xl w-full max-w-6xl max-h-[90vh] overflow-hidden animate-slide-up flex flex-col" onClick={(e) => e.stopPropagation()}>

              {/* Modal Header */}
              <div className="flex items-center justify-between px-6 py-4 border-b border-surface-200 dark:border-surface-700">
                <div>
                  <h3 className="font-semibold text-surface-900 dark:text-white">{preview.dataset?.name}</h3>
                  <p className="text-sm text-surface-400">
                    {processedRows.length.toLocaleString()} of {preview.totalRows?.toLocaleString()} rows
                    {searchQuery && ` matching "${searchQuery}"`}
                  </p>
                </div>
                <button onClick={() => setPreview(null)} className="p-2 rounded-lg hover:bg-surface-100 dark:hover:bg-surface-700">
                  <HiOutlineX className="w-5 h-5" />
                </button>
              </div>

              {/* Tabs */}
              <div className="flex gap-1 px-6 pt-3 border-b border-surface-100 dark:border-surface-700">
                <button
                  onClick={() => setActiveTab('data')}
                  className={`flex items-center gap-1.5 px-4 py-2 text-sm font-medium rounded-t-lg border-b-2 transition-colors ${activeTab === 'data' ? 'border-primary-500 text-primary-600 dark:text-primary-400' : 'border-transparent text-surface-500 hover:text-surface-700 dark:hover:text-surface-300'}`}
                >
                  <HiOutlineTable className="w-4 h-4" /> Data
                </button>
                <button
                  onClick={() => setActiveTab('profile')}
                  className={`flex items-center gap-1.5 px-4 py-2 text-sm font-medium rounded-t-lg border-b-2 transition-colors ${activeTab === 'profile' ? 'border-primary-500 text-primary-600 dark:text-primary-400' : 'border-transparent text-surface-500 hover:text-surface-700 dark:hover:text-surface-300'}`}
                >
                  <HiOutlineChartBar className="w-4 h-4" /> Data Profile
                </button>
                <div className="flex-1" />
                <button
                  onClick={handleAutoGenerateDashboard}
                  disabled={generatingDashboard}
                  className="flex items-center gap-1.5 px-4 py-1.5 mb-1.5 text-xs font-semibold rounded-lg bg-primary-500 text-white hover:bg-primary-600 disabled:opacity-50 transition-colors shadow-sm"
                >
                  {generatingDashboard ? (
                    <><div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin" /> Generating...</>
                  ) : (
                    <><HiOutlineSparkles className="w-3 h-3" /> Auto-Generate Dashboard</>
                  )}
                </button>
              </div>

              {activeTab === 'data' && (
                <>
                  {/* Search Bar */}
                  <div className="px-6 py-3 border-b border-surface-100 dark:border-surface-700">
                    <div className="relative">
                      <HiOutlineSearch className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-surface-400" />
                      <input
                        type="text"
                        placeholder="Search in data..."
                        value={searchQuery}
                        onChange={e => { setSearchQuery(e.target.value); setCurrentPage(1); }}
                        className="w-full pl-9 pr-4 py-2 text-sm rounded-lg border border-surface-200 dark:border-surface-600 bg-surface-50 dark:bg-surface-900 text-surface-900 dark:text-white placeholder-surface-400 focus:outline-none focus:ring-2 focus:ring-primary-400"
                      />
                    </div>
                  </div>

                  {/* Table */}
                  <div className="overflow-auto flex-1">
                    {previewLoading ? (
                      <div className="flex justify-center py-12">
                        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-500" />
                      </div>
                    ) : (
                      <table className="w-full text-sm">
                        <thead className="bg-surface-50 dark:bg-surface-900 sticky top-0">
                          <tr>
                            {preview.dataset?.columns?.map((col, i) => (
                              <th
                                key={i}
                                className="px-4 py-3 text-left font-semibold text-surface-700 dark:text-surface-300 whitespace-nowrap cursor-pointer hover:bg-surface-100 dark:hover:bg-surface-700 select-none"
                                onClick={() => handleSort(col.name)}
                              >
                                <div className="flex items-center gap-1">
                                  <span>{col.name}</span>
                                  <span className={`text-xs font-normal ${col.dataType === 'NUMBER' ? 'text-blue-500' : 'text-emerald-500'}`}>
                                    {col.dataType}
                                  </span>
                                  {sortCol === col.name ? (
                                    sortDir === 'asc'
                                      ? <HiOutlineChevronUp className="w-3 h-3 text-primary-500" />
                                      : <HiOutlineChevronDown className="w-3 h-3 text-primary-500" />
                                  ) : (
                                    <span className="w-3 h-3 opacity-0 group-hover:opacity-30">↕</span>
                                  )}
                                </div>
                              </th>
                            ))}
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-surface-100 dark:divide-surface-700">
                          {pagedRows.length === 0 ? (
                            <tr>
                              <td colSpan={preview.dataset?.columns?.length || 1} className="px-4 py-8 text-center text-surface-400 italic">
                                No rows match your search
                              </td>
                            </tr>
                          ) : pagedRows.map((row, i) => (
                            <tr key={i} className="hover:bg-surface-50 dark:hover:bg-surface-700/50">
                              {preview.dataset?.columns?.map((col, j) => (
                                <td key={j} className="px-4 py-2.5 text-surface-600 dark:text-surface-400 whitespace-nowrap">
                                  {row[col.name] != null ? String(row[col.name]) : <span className="text-surface-300 italic">null</span>}
                                </td>
                              ))}
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    )}
                  </div>

                  {/* Pagination */}
                  {totalPages > 1 && (
                    <div className="flex items-center justify-between px-6 py-3 border-t border-surface-100 dark:border-surface-700">
                      <span className="text-xs text-surface-400">
                        Page {currentPage} of {totalPages} · {processedRows.length.toLocaleString()} rows
                      </span>
                      <div className="flex gap-1">
                        <button
                          onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                          disabled={currentPage === 1}
                          className="px-3 py-1.5 text-xs rounded-lg border border-surface-200 dark:border-surface-600 hover:bg-surface-50 dark:hover:bg-surface-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                        >
                          Previous
                        </button>
                        {Array.from({ length: Math.min(5, totalPages) }, (_, i) => {
                          const page = currentPage <= 3
                            ? i + 1
                            : currentPage >= totalPages - 2
                              ? totalPages - 4 + i
                              : currentPage - 2 + i;
                          if (page < 1 || page > totalPages) return null;
                          return (
                            <button
                              key={page}
                              onClick={() => setCurrentPage(page)}
                              className={`px-3 py-1.5 text-xs rounded-lg border transition-colors ${
                                currentPage === page
                                  ? 'bg-primary-500 border-primary-500 text-white'
                                  : 'border-surface-200 dark:border-surface-600 hover:bg-surface-50 dark:hover:bg-surface-700'
                              }`}
                            >
                              {page}
                            </button>
                          );
                        })}
                        <button
                          onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                          disabled={currentPage === totalPages}
                          className="px-3 py-1.5 text-xs rounded-lg border border-surface-200 dark:border-surface-600 hover:bg-surface-50 dark:hover:bg-surface-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                        >
                          Next
                        </button>
                      </div>
                    </div>
                  )}
                </>
              )}

              {activeTab === 'profile' && (
                <div className="overflow-auto flex-1 p-6">
                  {/* AI Summary Section */}
                  <div className="mb-6 p-4 rounded-xl bg-gradient-to-r from-primary-50 via-purple-50 to-indigo-50 dark:from-primary-900/15 dark:via-purple-900/15 dark:to-indigo-900/15 border border-primary-100 dark:border-primary-800/30">
                    <div className="flex items-center justify-between mb-2">
                      <div className="flex items-center gap-2">
                        <HiOutlineSparkles className="w-4 h-4 text-primary-500" />
                        <h4 className="text-sm font-semibold text-primary-700 dark:text-primary-400">AI Data Summary</h4>
                      </div>
                      <button
                        onClick={async () => {
                          setSummaryLoading(true);
                          setAiSummary('');
                          try {
                            const profilePayload = {
                              datasetName: preview.dataset?.name,
                              totalRows: preview.totalRows,
                              totalColumns: preview.dataset?.columns?.length,
                              columns: profileStats.map(s => ({
                                name: s.name, type: s.type, nullCount: s.nullCount,
                                unique: s.unique, total: s.total,
                                ...(s.type === 'NUMBER' ? { min: s.min, max: s.max, avg: s.avg } : { topValue: s.topValue, topCount: s.topCount }),
                              })),
                            };
                            const res = await aiApi.summarize(profilePayload);
                            setAiSummary(res.data.summary || res.data.error || 'No summary generated');
                          } catch (err) {
                            setAiSummary('Failed to generate summary: ' + (err.response?.data?.error || err.message));
                          } finally {
                            setSummaryLoading(false);
                          }
                        }}
                        disabled={summaryLoading}
                        className="text-xs px-3 py-1.5 rounded-lg bg-primary-500 text-white hover:bg-primary-600 disabled:opacity-50 flex items-center gap-1.5 transition-colors"
                      >
                        {summaryLoading ? (
                          <><div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin" /> Analyzing...</>
                        ) : (
                          <><HiOutlineSparkles className="w-3 h-3" /> Generate Summary</>
                        )}
                      </button>
                    </div>
                    {aiSummary ? (
                      <p className="text-sm text-surface-700 dark:text-surface-300 leading-relaxed">{aiSummary}</p>
                    ) : (
                      <p className="text-xs text-surface-400 italic">Click "Generate Summary" to get an AI-powered analysis of this dataset</p>
                    )}
                  </div>

                  <p className="text-sm text-surface-500 dark:text-surface-400 mb-4">
                    Statistics computed on the preview sample ({preview.previewRows} rows)
                  </p>
                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                    {profileStats.map((stat, i) => (
                      <div key={i} className="p-4 rounded-xl border border-surface-200 dark:border-surface-700 bg-surface-50 dark:bg-surface-900 space-y-2">
                        <div className="flex items-center justify-between">
                          <h4 className="font-semibold text-surface-900 dark:text-white text-sm truncate">{stat.name}</h4>
                          <span className={`text-xs px-2 py-0.5 rounded-full font-medium shrink-0 ml-2 ${typeColors[stat.type] || typeColors.STRING}`}>
                            {stat.type}
                          </span>
                        </div>
                        <div className="space-y-1 text-xs text-surface-500 dark:text-surface-400">
                          <div className="flex justify-between">
                            <span>Total rows</span><span className="font-medium text-surface-700 dark:text-surface-300">{stat.total.toLocaleString()}</span>
                          </div>
                          <div className="flex justify-between">
                            <span>Null values</span>
                            <span className={`font-medium ${stat.nullCount > 0 ? 'text-amber-500' : 'text-emerald-500'}`}>
                              {stat.nullCount} ({Math.round((stat.nullCount / stat.total) * 100)}%)
                            </span>
                          </div>
                          <div className="flex justify-between">
                            <span>Unique values</span><span className="font-medium text-surface-700 dark:text-surface-300">{stat.unique?.toLocaleString()}</span>
                          </div>
                          {stat.type === 'NUMBER' ? (
                            <>
                              <div className="flex justify-between"><span>Min</span><span className="font-medium text-surface-700 dark:text-surface-300">{stat.min ?? '—'}</span></div>
                              <div className="flex justify-between"><span>Max</span><span className="font-medium text-surface-700 dark:text-surface-300">{stat.max ?? '—'}</span></div>
                              <div className="flex justify-between"><span>Average</span><span className="font-medium text-surface-700 dark:text-surface-300">{stat.avg ?? '—'}</span></div>
                            </>
                          ) : (
                            <>
                              <div className="flex justify-between gap-2">
                                <span>Top value</span><span className="font-medium text-surface-700 dark:text-surface-300 truncate max-w-[120px]">{stat.topValue ?? '—'}</span>
                              </div>
                              <div className="flex justify-between"><span>Top frequency</span><span className="font-medium text-surface-700 dark:text-surface-300">{stat.topCount}</span></div>
                            </>
                          )}
                        </div>
                        {/* Null indicator bar */}
                        <div className="h-1.5 rounded-full bg-surface-200 dark:bg-surface-700 overflow-hidden">
                          <div
                            className="h-full rounded-full bg-emerald-400"
                            style={{ width: `${100 - Math.round((stat.nullCount / stat.total) * 100)}%` }}
                          />
                        </div>
                        <p className="text-[10px] text-surface-400">Fill rate: {100 - Math.round((stat.nullCount / stat.total) * 100)}%</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </AppLayout>
  );
}
